config/routes.rb
Rails.application.routes.draw do
  
  resources :appointements do 
    get '/report', to: 'appointements#report', on: :member
    get '/report_mail', to: 'appointements#report_mail', on: :member
  end

  resources :indicators
  resources :patients
 
  root 'appointements#index'
  

end

app/models/appointement.rb
class Appointement < ActiveRecord::Base
  belongs_to :patient
  has_many :appointement_indicators

  validates :patient_id, presence: true

  accepts_nested_attributes_for :appointement_indicators
end

app/models/appointement_indicator.rb
class AppointementIndicator < ActiveRecord::Base
  belongs_to :appointement
  belongs_to :indicator
end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  has_many :appointement_indicators
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointements

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointements_controller.rb
class AppointementsController < ApplicationController
  before_action :set_appointement, only: [:show, :edit, :update, :destroy, :report, :report_mail]

  def index
    @appointements = Appointement.all
  end

  def show
  end

  def new
    @appointement = Appointement.new
    @appointement.appointement_indicators.build
  end

  def edit
  end

  def create
    @appointement = Appointement.new(appointement_params)

    respond_to do |format|
      if @appointement.save
        format.html { redirect_to @appointement, notice: 'Appointement was successfully created.' }
        format.json { render :show, status: :created, location: @appointement }
      else
        format.html { render :new }
        format.json { render json: @appointement.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @appointement.update(appointement_params)
        format.html { redirect_to @appointement, notice: 'Appointement was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointement }
      else
        format.html { render :edit }
        format.json { render json: @appointement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointement.destroy
    respond_to do |format|
      format.html { redirect_to appointements_url, notice: 'Appointement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def report
    respond_to do |format|
      format.html
      format.pdf do
       render pdf: "#{@appointement.id}_report.pdf",
         template: 'appointements/report.html.erb', encoding: 'UTF-8'
      end
    end
  end
  
  def report_mail
    pdf_report = render_to_string pdf: 'report',
      template: 'appointements/report.html.erb', encoding: 'UTF-8'
    
    ReportMailer.patient_report(@appointement.patient, pdf_report ).deliver
    render nothing: true
  end

  private
    def set_appointement
      @appointement = Appointement.find(params[:id])
    end

    def appointement_params
      params.require(:appointement).permit(:patient_id, :description, 
        appointement_indicators_attributes: [:indicator_id, :result])
    end
end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  before_action :set_indicator, only: [:show, :edit, :update, :destroy]

  # GET /indicators
  # GET /indicators.json
  def index
    @indicators = Indicator.all
  end

  # GET /indicators/1
  # GET /indicators/1.json
  def show
  end

  # GET /indicators/new
  def new
    @indicator = Indicator.new
  end

  # GET /indicators/1/edit
  def edit
  end

  # POST /indicators
  # POST /indicators.json
  def create
    @indicator = Indicator.new(indicator_params)

    respond_to do |format|
      if @indicator.save
        format.html { redirect_to @indicator, notice: 'Indicator was successfully created.' }
        format.json { render :show, status: :created, location: @indicator }
      else
        format.html { render :new }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicators/1
  # PATCH/PUT /indicators/1.json
  def update
    respond_to do |format|
      if @indicator.update(indicator_params)
        format.html { redirect_to @indicator, notice: 'Indicator was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicator }
      else
        format.html { render :edit }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1
  # DELETE /indicators/1.json
  def destroy
    @indicator.destroy
    respond_to do |format|
      format.html { redirect_to indicators_url, notice: 'Indicator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicator
      @indicator = Indicator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicator_params
      params.require(:indicator).permit(:name, :range)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :sex, :date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_indicators(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_indicators", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/appointements_helper.rb
module AppointementsHelper
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointements/_appointement_indicator_fields.html.erb
<li>
  <%= f.collection_select :indicator_id, Indicator.all, :id, :name, include_blank: true %>
  <%= f.text_field :result %><br>
</li>  

app/views/appointements/_form.html.erb
<%= form_for @appointement do |f| %>
  <% if @appointement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointement.errors.count, "error") %> prohibited this appointement from being saved:</h2>

      <ul>
      <% @appointement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient %><br>
    <%= f.collection_select :patient_id, Patient.all, :id, :name, include_blank: true %><br>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <p> Indicators </p>
    <%= link_to_add_indicators "Add Indicator", f, :appointement_indicators %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/appointements/edit.html.erb
<h1>Editing Appointement</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointement %> |
<%= link_to 'Back', appointements_path %>

app/views/appointements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointements</h1>

<table>
  <thead>
    <tr>
      <th>References</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointements.each do |appointement| %>
      <tr>
        <td><%= appointement.patient.name %></td>
        <td><%= appointement.description %></td>
        <td><%= link_to 'Show', appointement %></td>
        <td><%= link_to 'Edit', edit_appointement_path(appointement) %></td>
        <td><%= link_to 'Destroy', appointement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Destroy', appointement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Print', report_appointement_path(appointement) %></td>
        <td><%= link_to 'Send mail', report_mail_appointement_path(appointement) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointement', new_appointement_path %>

app/views/appointements/new.html.erb
<h1>New Appointement</h1>

<%= render 'form' %>

<%= link_to 'Back', appointements_path %>

app/views/appointements/report.html.erb
<h2>Patient report</h2>

<div class="report_header">
  <h3><%= @appointement.patient.first_name.capitalize %> <%= @appointement.patient.last_name.capitalize %></h3>
</div>

<div class="indicators">
  <table>
    <thead>
      <tr>
        <th>Indicator</th>
        <th>Result</th>
        <th>Range</th>
      </tr>
    </thead>

    <tbody>
      <% @appointement.appointement_indicators.each do |indicator| %>
        <tr>
          <td><%= indicator.indicator.name %></td>
          <td><%= indicator.result %></td>
          <td><%= indicator.range %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/appointements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient:</strong>
  <%= @appointement.patient.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appointement.description %>
</p>

<%= link_to 'Edit', edit_appointement_path(@appointement) %> |
<%= link_to 'Back', appointements_path %>

app/views/indicators/_form.html.erb
<%= form_for(@indicator) do |f| %>
  <% if @indicator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indicator.errors.count, "error") %> prohibited this indicator from being saved:</h2>

      <ul>
      <% @indicator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :range %><br>
    <%= f.text_field :range %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/indicators/edit.html.erb
<h1>Editing Indicator</h1>

<%= render 'form' %>

<%= link_to 'Show', @indicator %> |
<%= link_to 'Back', indicators_path %>

app/views/indicators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Indicators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Range</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indicators.each do |indicator| %>
      <tr>
        <td><%= indicator.name %></td>
        <td><%= indicator.range %></td>
        <td><%= link_to 'Show', indicator %></td>
        <td><%= link_to 'Edit', edit_indicator_path(indicator) %></td>
        <td><%= link_to 'Destroy', indicator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indicator', new_indicator_path %>

app/views/indicators/new.html.erb
<h1>New Indicator</h1>

<%= render 'form' %>

<%= link_to 'Back', indicators_path %>

app/views/indicators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @indicator.name %>
</p>

<p>
  <strong>Range:</strong>
  <%= @indicator.range %>
</p>

<%= link_to 'Edit', edit_indicator_path(@indicator) %> |
<%= link_to 'Back', indicators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PatientReport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Sex</th>
      <th>Date of birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.sex %></td>
        <td><%= patient.date_of_birth %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @patient.sex %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @patient.date_of_birth %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>